-- Motion Matrix Supabase Database Schema

-- -------------------------------------------------------------
-- 1. Create leads table
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  company TEXT,
  phone TEXT,
  service TEXT,
  message TEXT,
  source TEXT DEFAULT 'website_lead_form',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for leads
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Allow anyone to submit a lead (Anonymous Insert)
CREATE POLICY "Allow anonymous lead inserts" ON leads
  FOR INSERT
  WITH CHECK (true);


-- -------------------------------------------------------------
-- 2. Create categories table
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for categories
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- Allow public read access to categories
CREATE POLICY "Allow public read categories" ON categories
  FOR SELECT
  USING (true);


-- -------------------------------------------------------------
-- 3. Create tags table
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for tags
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;

-- Allow public read access to tags
CREATE POLICY "Allow public read tags" ON tags
  FOR SELECT
  USING (true);


-- -------------------------------------------------------------
-- 4. Create blog_posts table
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  meta_title TEXT,
  meta_description TEXT,
  featured_image TEXT,
  content TEXT NOT NULL,
  author_name TEXT NOT NULL,
  author_avatar TEXT,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  published_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for blog_posts
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

-- Allow public read access to blog_posts
CREATE POLICY "Allow public read blog_posts" ON blog_posts
  FOR SELECT
  USING (true);


-- -------------------------------------------------------------
-- 5. Create junction table for posts and tags (Many-to-Many)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS blog_posts_tags (
  post_id BIGINT REFERENCES blog_posts(id) ON DELETE CASCADE,
  tag_id BIGINT REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, tag_id)
);

-- Enable RLS for junction table
ALTER TABLE blog_posts_tags ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read blog_posts_tags" ON blog_posts_tags
  FOR SELECT
  USING (true);


-- -------------------------------------------------------------
-- 6. Create portfolio_projects table
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS portfolio_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  image_url TEXT NOT NULL,
  project_url TEXT,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for portfolio
ALTER TABLE portfolio_projects ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read portfolio_projects" ON portfolio_projects
  FOR SELECT
  USING (true);


-- -------------------------------------------------------------
-- 7. Insert seed data
-- -------------------------------------------------------------

-- Seed Categories
INSERT INTO categories (name, slug) VALUES
  ('Creative Strategy', 'creative-strategy'),
  ('Performance Marketing', 'performance-marketing'),
  ('AI Automation', 'ai-automation'),
  ('Brand Growth', 'brand-growth')
ON CONFLICT (slug) DO NOTHING;

-- Seed Tags
INSERT INTO tags (name, slug) VALUES
  ('AI', 'ai'),
  ('Design', 'design'),
  ('Marketing', 'marketing'),
  ('Automation', 'automation'),
  ('Copywriting', 'copywriting')
ON CONFLICT (slug) DO NOTHING;

-- Seed Blog Posts
INSERT INTO blog_posts (title, slug, meta_title, meta_description, featured_image, content, author_name, category_id) VALUES
  (
    'How AI Automation Can Double Your Agency Creative Output', 
    'ai-automation-double-creative-output', 
    'Double Creative Output with AI Automation | Motion Matrix', 
    'Learn how high-performing creative agencies leverage AI-powered workflows to execute faster, reduce production overhead, and scale content volume.',
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    '<h2>The Shift to AI-Powered Systems</h2><p>For modern brands, scaling creative assets is no longer a luxury—it is a survival necessity. In this article, we cover how Motion Matrix leverages automated pipelines to deliver results-focused creative growth at scale. By combining AI workflow systems with founder-led creative direction, you can cut execution time in half while maintaining a premium brand identity.</p><h3>Why Execution Speed Matters</h3><p>Traditional creative agencies are slow. Multiple revision cycles, bloated communication layers, and lack of standard tooling lead to delays. A streamlined workflow utilizing AI tools can automate repetitive production tasks like asset resizing, version creation, and basic formatting, freeing up creative directors to focus on strategy and high-level design.</p>',
    'Chandan S',
    (SELECT id FROM categories WHERE slug = 'ai-automation' LIMIT 1)
  ),
  (
    'Redesigning Your Visual Identity for Maximum Creative Growth', 
    'redesigning-visual-identity-creative-growth', 
    'Visual Identity Redesign for Creative Growth | Motion Matrix', 
    'Discover our structured process for executing a brand refresh that builds authority, improves user trust, and scales conversion metrics.',
    'https://images.unsplash.com/photo-1634973357973-f2ed255753e1?q=80&w=800&auto=format&fit=crop',
    '<h2>The Anatomy of a Modern Refresh</h2><p>A brand guideline is not just a collection of color codes and fonts; it is the visual infrastructure that drives company authority. High-end growth agencies like Linear or Contra leverage extreme typography contrast, harmonized colorways, and a single signature element (like a hard offset shadow) to stand out.</p><h3>Rules of Visual Structure</h3><ul><li><strong>Color Constraints:</strong> Restrict your brand palette to three primary colors to maintain clean layout hierarchy. Use a bold accent color purely as a marker highlight.</li><li><strong>Typography Contrast:</strong> Pair a high-impact condensed display font with a humanist, neutral body typeface to maximize visual hierarchy.</li><li><strong>Motif System:</strong> Hard offset borders and flat container drop shadows establish a tactile, premium feeling.</li></ul>',
    'Chandan S',
    (SELECT id FROM categories WHERE slug = 'brand-growth' LIMIT 1)
  )
ON CONFLICT (slug) DO NOTHING;

-- Seed Portfolio Projects
INSERT INTO portfolio_projects (title, category, image_url, project_url, sort_order) VALUES
  (
    'Simplifying Complexity',
    'Explainer Videos',
    'https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=800&auto=format&fit=crop',
    'https://dribbble.com/shots/26396711-Explainer-Videofolio',
    1
  ),
  (
    'Authentic Stories',
    'Testimonial Videos',
    'https://images.unsplash.com/photo-1542744094-3a31f103e35f?q=80&w=800&auto=format&fit=crop',
    'https://dribbble.com/shots/26396561-Testimonial-Video-Series',
    2
  ),
  (
    'Audio & Visual Excellence',
    'Podcast Production',
    'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?q=80&w=800&auto=format&fit=crop',
    'https://dribbble.com/shots/26396458-Refyne-Podcast',
    3
  ),
  (
    'Campaign Assets',
    'Marketing Creatives',
    'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?q=80&w=800&auto=format&fit=crop',
    'https://dribbble.com/shots/26396432-Refyne-Graphic-Visual-Design-for-Marketing-Collaterals',
    4
  ),
  (
    'Conversion Drivers',
    'Performance Marketing Campaigns',
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop',
    'https://dribbble.com/shots/26396658-Performance-Ad-Portfolio',
    5
  );
